// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATU0ZWKZBu2oykBUIaEIz4kHYlDsl_S-Q',
    appId: '1:1017503176651:web:ab8728aee9dbc9a214084e',
    messagingSenderId: '1017503176651',
    projectId: 'pixelpioneercpplink',
    authDomain: 'pixelpioneercpplink.firebaseapp.com',
    storageBucket: 'pixelpioneercpplink.appspot.com',
    measurementId: 'G-PEWZN3ZXXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwJ3XYKfu5D69iLoaZvCKiqEcWLN-CB4',
    appId: '1:1017503176651:android:782730a78e40d54f14084e',
    messagingSenderId: '1017503176651',
    projectId: 'pixelpioneercpplink',
    storageBucket: 'pixelpioneercpplink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAPByWxA3aWi837PTNswLjJdzve1S68s',
    appId: '1:1017503176651:ios:1aa0e2670d6b929714084e',
    messagingSenderId: '1017503176651',
    projectId: 'pixelpioneercpplink',
    storageBucket: 'pixelpioneercpplink.appspot.com',
    iosBundleId: 'com.example.pixelpioneerCpplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgAPByWxA3aWi837PTNswLjJdzve1S68s',
    appId: '1:1017503176651:ios:1aa0e2670d6b929714084e',
    messagingSenderId: '1017503176651',
    projectId: 'pixelpioneercpplink',
    storageBucket: 'pixelpioneercpplink.appspot.com',
    iosBundleId: 'com.example.pixelpioneerCpplink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATU0ZWKZBu2oykBUIaEIz4kHYlDsl_S-Q',
    appId: '1:1017503176651:web:def05861b5e0cf7214084e',
    messagingSenderId: '1017503176651',
    projectId: 'pixelpioneercpplink',
    authDomain: 'pixelpioneercpplink.firebaseapp.com',
    storageBucket: 'pixelpioneercpplink.appspot.com',
    measurementId: 'G-DTX7FSDXDB',
  );
}
